export class StorageConstants {
  /**
   * DEFAULT_PREF
   * 默认首选项表
   */
  static readonly DEFAULT_PREF: string = "default_pref"

  // Preferences keys
  /**
   * PREFKEY_DARK_MODE
   * 首选项key - dark mode
   */
  static readonly PREFKEY_DARK_MODE: string = 'dark_mode';
  /**
   * PREFKEY_LANGUAGE
   * 首选项key - language
   */
  static readonly PREFKEY_LANGUAGE: string = 'language';
  /**
   * PREFKEY_CUSTOM_APIS
   * 首选项key - custom apis
   */
  static readonly PREFKEY_CUSTOM_APIS: string = "custom_apis";
  /**
   * PREFKEY_OFFICIAL_APIS
   * 首选项key - official apis
   */
  static readonly PREFKEY_OFFICIAL_APIS: string = "official_apis";
  /**
   * PREFKEY_CURRENT_ACTIVE_API
   * 首选项key - current active api
   */
  static readonly PREFKEY_CURRENT_ACTIVE_API: string = "cur_active_api";
}